apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;

      # Proxy all API calls to the backend service inside the cluster
      # NOTE: proxy_pass WITHOUT trailing slash preserves the original request URI,
      # so /api/users -> http://backend-service:8080/api/users (no path rewrite).
      location /api/ {
        proxy_pass http://backend-service:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_buffering off;
      }

      # Serve static frontend and fallback to index.html for SPA routing
      location / {
        try_files $uri $uri/ /index.html;
      }
    }